//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReporteCOVID19Back
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCat_Programas
    {
        public long ID { get; set; }
        public string Clave { get; set; }
        public string Descripcion { get; set; }
        public string Clave_nivel { get; set; }
        public string Clave_escuela { get; set; }
        public string Campus { get; set; }
        public bool Activo { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
