//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReporteCOVID19Back
{
    using System;
    using System.Collections.Generic;
    
    public partial class QPA_SeleccionBloqueados
    {
        public long RN { get; set; }
        public string PERIODO { get; set; }
        public string Alumno_IDSIU { get; set; }
        public Nullable<int> NRC { get; set; }
        public string CAMPUS { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Alumno_Apellidos { get; set; }
        public string Alumno_Nombres { get; set; }
        public string Alumno_Telefono { get; set; }
        public string Alumno_O365 { get; set; }
        public string CveMateria { get; set; }
        public string NombreMateria { get; set; }
        public string Cve_Escuela { get; set; }
        public string ListaCruzada { get; set; }
        public string Docente_IDSIU { get; set; }
        public string Docente_Nombres { get; set; }
        public string Docente_Apellidos { get; set; }
        public string Docente_O365 { get; set; }
        public Nullable<System.DateTime> UltimaVisita { get; set; }
        public Nullable<System.DateTime> FechaRegreso { get; set; }
    }
}
